runtime: php55
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js)$
  application_readable: true
- url: /
  script: index.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
